
#Inventory sorter blacklists
[blacklists]
	#Container blacklist
	containerBlacklist = ["titanium:addon_container", "botania:flower_bag"]
	#Slot type blacklist
	slotBlacklist = ["net.p3pp3rf1y.sophisticatedcore.upgrades.FilterLogicContainer$FilterLogicSlot", "net.p3pp3rf1y.sophisticatedcore.common.gui.SlotSuppliedHandler", "net.p3pp3rf1y.sophisticatedcore.common.gui.FilterSlotItemHandler", "net.p3pp3rf1y.sophisticatedcore.common.gui.StorageInventorySlot", "net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase$StorageUpgradeSlot"]

